# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish OpenAPI axios library

on:
  workflow_dispatch:
  release:
    types: [created]
env:
  NPM_PKG_NAME: "@${{github.repository}}"

jobs:
  get-openapi-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3.1.4
      - run: pip install -r requirements.txt
      - run: python build.py
      - uses: actions/upload-artifact@v3.1.2
        with: 
          name: openapi.json
          path: dist/openapi.json
          
      

  publish-gpr:
    needs: get-openapi-json
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo $NPM_PKG_NAME
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: actions/download-artifact@v2.1.1
        with:
          name: openapi.json
      - run: npx -y @openapitools/openapi-generator-cli generate -g typescript-axios -i openapi.json -p npmName=@${{github.repository}}
      - run: |
          echo "@${{github.repository_owner}}:registry=https://npm.pkg.github.com" > .npmrc
          npm pkg set repository.url=${{github.event.repository.url}} private=true publishConfig.registry=https://npm.pkg.github.com/
          npm pkg delete license
          npm install 
          npm run build
      - uses: actions/upload-artifact@v3.1.2
        path: .
      - run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
